version: '3'
services:
  db:
    image: postgres
    ports:
      - '5432:5432' 
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    tty: true
    stdin_open: true
    depends_on:
      - db 
    ports:
      - "3000:3000" 
    volumes:
      - .:/turnapp
volumes:
  postgresql-data:
    driver: local